[package]
name = "teo-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teo = { path = "../teo", features = ["data-source-mongodb"] }
tokio = { version = "1.18", features = ["macros"] }